# Generated by Django 4.0.10 on 2024-05-12 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(help_text='Car model', max_length=128)),
                ('year', models.IntegerField(help_text='Car year')),
                ('price', models.FloatField(help_text='Car price')),
            ],
        ),
    ]
