# Generated by Django 4.0.10 on 2024-05-12 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tsd', '0002_car'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='mileage',
            field=models.FloatField(default=100, help_text='Car mileage'),
        ),
    ]
